version: '3.8'

services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./backend/static_files:/www/media
    depends_on:
      - backend
      - frontend
    networks:
      - servers

  backend:
    build: ./backend/
    env_file:
      - ./backend/.env
    ports:
      - 7507:7507
    networks:
      - servers
      - postgres_db
    depends_on:
      - db
    volumes:
      - ./backend/innopoints:/app/innopoints        # To detect file changes. Dev only
      - ./backend/static_files:/app/static_files
      - type: bind
        source: ./backend/db.sqlite3
        target: /app/db.sqlite3

  frontend:
    build: ./frontend/
    env_file:
      - ./frontend/.env
    networks:
      - servers
    ports:
      - 3000:3000
      - 10000:10000       # For Sapper something. Dev only
    volumes:
      - ./frontend/src:/app/src    # To detect changes. Dev only
      - ./frontend/static:/app/static    # To detect changes. Dev only

  db:
    image: postgres:12.1-alpine
    env_file:
      - ./.env
    networks:
      - postgres_db
    ports:
      - 5432:5432                 # For pgAdmin. Dev only
    volumes:
      - database:/var/lib/postgresql/data

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /app/swagger.yaml
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./backend/swagger.yaml
        target: /app/swagger.yaml
        read_only: true

networks:
  servers:
    driver: bridge
  postgres_db:
    driver: bridge

volumes:
  database:
