version: '3'

services:
  # nginx:
  #   build: ./nginx/
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - servers

  caddy:
    build: ./caddy/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    networks:
      - servers

  backend:
    build: ./backend/
    env_file:
      - ./backend/.env
    networks:
      - servers
      - postgres_db
    depends_on:
      - db
    volumes:
      - ./backend/innopoints:/app/innopoints        # To detect file changes. Dev only
      - ./backend/static_files:/app/static_files

  frontend:
    build: ./frontend/
    env_file:
      - ./frontend/.env
    networks:
      - servers
    ports:
      - 10000:10000       # For Sapper something. Dev only
    volumes:
      - ./frontend/src:/app/src    # To detect changes. Dev only
      - ./frontend/static:/app/static    # To detect changes. Dev only

  db:
    image: postgres:12.1-alpine
    env_file:
      - ./.env
    networks:
      - postgres_db
    ports:
      - 5432:5432                 # For pgAdmin. Dev only
    volumes:
      - database:/var/lib/postgresql/data

networks:
  servers:
    driver: bridge
  postgres_db:
    driver: bridge

volumes:
  database:
